#!/usr/bin/env bash
# scripts/embed.sh — 将 frontend/dist/ 嵌入为 embedded.mbt
set -euo pipefail

DIST="frontend/dist"
OUT="embedded.mbt"

if [ ! -d "$DIST" ]; then
  echo "error: $DIST not found; run 'make build-frontend' first" >&2
  exit 1
fi

cat > "$OUT" <<'HEADER'
// Code generated by scripts/embed.sh; DO NOT EDIT.

pub let emb_paths : Array[String] = [
HEADER

# Collect file list
FILES=()
while IFS= read -r -d '' f; do
  rel="${f#$DIST}"
  FILES+=("$rel")
  echo "  \"$rel\"," >> "$OUT"
done < <(find "$DIST" -type f -print0 | sort -z)

cat >> "$OUT" <<'MID2'
]

pub let emb_data : Array[String] = [
MID2

for f in "${FILES[@]}"; do
  src="$DIST$f"
  b64=$(base64 -w0 < "$src" 2>/dev/null || base64 < "$src" | tr -d '\n')
  echo "  \"$b64\"," >> "$OUT"
done

echo ']' >> "$OUT"

echo "generated $OUT: ${#FILES[@]} files embedded" >&2
